version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123  
    ports:
      - "1433:1433"

  packagingapi:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - backend

networks:
  backend:
    driver: bridge
